application: abelana-222
module: default
version: 1

runtime: go
api_version: go1

#instance_class: F1
#automatic_scaling:

handlers:
# root url
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /d/gitkit
  script: _go_app
  secure: always

- url: /d/signOut
  script: _go_app
  secure: always

- url: /d/oobAction
  script: _go_app
  secure: always

- url: /d/update
  script: _go_app
  secure: always

- url: /d/deleteAccount
  script: _go_app
  secure: always

- url: /img/*
  static_dir: static/img
  secure: always

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /*
  static_dir: static/
  secure: always
