module: default
version: 1

runtime: python27
api_version: 1
threadsafe: yes

#instance_class: F1
#automatic_scaling:

handlers:
# root url
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /img/*
  static_dir: static/img
  secure: always

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

# for now all html files will be served statically.
- url: /(.*\.html)$
  static_files: static/\1
  upload: static/*.html
  secure: always
