application: abelana-222
module: endpoints
version: 1

runtime: go
api_version: go1

instance_class: F4
automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms
  max_concurrent_requests: 100

handlers:

# Make sure our requests make it to our app

  - url: /photopush/.*
    script: _go_app
    secure: always
#    login: admin

  - url: /_ah/spi/.*
    script: _go_app
    secure: always

  - url: /private
    application_readable: true
    static_dir: private
    secure: always
    login: admin

  - url: /.*
    script: _go_app
    secure: always
